BACKLOG-21146 Update publication action
Jahia/jackrabbit pull request #11
Opened 2024-04-04 19:26 UTC by AKarmanov

## JIRA

https://jira.jahia.org/browse/BACKLOG-21146

## Description

Update publication action

2024-04-04 20:13 UTC, gflores-jahia requested changes
I'm not sure if this is the right flow for thirdparty builds but we can try. But can we maybe at least try to build with jdk 8 container (since it uses jvm 8 before)

2024-04-05 12:26 UTC, cedmail requested changes
I doubt it is the correct solution for the problem, I have updated on release to use v4 of the actions so we should do this here

2024-04-05 13:31 UTC, gflores-jahia commented on .github/workflows/on-merge.yml
> +      image: jahia/cimg-mvn-cache:ga_cimg_openjdk_11.0.20-node
ok to use jdk 11 here but use jdk 1.8 in the maven deploy? or do we switch this to jdk 8?

2024-04-05 13:33 UTC, gflores-jahia approved these changes

2024-04-05 13:43 UTC, merged