TECH-1379: Update to 2.20.12
Jahia/jackrabbit pull request #4
Opened 2023-09-13 16:43 UTC by gflores-jahia

## JIRA

https://jira.jahia.org/browse/TECH-1379

## Description

* Update 2.20 branch, up to prior to 2.20 release
* Create TECH-1379 branch based off 2.20-jahia1 branch
* Merge 2.20 branch into TECH-1379 and resolve conflicts

2023-09-13 16:56 UTC, cedmail requested changes

2023-09-13 16:56 UTC, cedmail commented on jackrabbit-parent/pom.xml
> +>>>>>>> 2.20
Please fix this pom.xml

2023-09-13 17:50 UTC, gflores-jahia commented on jackrabbit-parent/pom.xml
> +>>>>>>> 2.20
Fixed, thanks

2023-09-14 12:32 UTC, cedmail approved these changes

2023-09-14 12:33 UTC, merged